### ISSUE TITLE
An excellent project!!

### ISSUE THREAD

**Issue by shie-ld** [daongochieu2810/CppAlgoTrading#1]
Truly appreciate you for this work. Btw, can you please add some documentation about how is the program working, what's the workflow of execution and a little bit of technical documentation too. It will be very helpful.

**Comment by daongochieu2810** [comment]
Yes sure thing! I'm a bit busy with other projects rn but I will make time to update the docs

**Comment by daongochieu2810** [comment]
@shie-ld Some rough dev guide added, let me know if you are still confused by anything. I will spend some time on the IBKR side for now
